### ISSUE TITLE
[BUG] alerts

### ISSUE THREAD

**Issue by Exyztence** [qbcore-framework/qb-bankrobbery#102]
Police alerts are not working fine, they are being shown in different locations or on locations of officers. Sometimes also there are x10 alerts on the same bank robbery and they are all in different places. It's the same issue as qb-storerobbery 
![image](https://user-images.githubusercontent.com/49649458/202912693-187983bd-7e2c-470f-a09f-7f9dac9fe7c6.png)

**Comment by ry304** [comment]
My server is also having the same issue. I am going to test to see if the same fix from Storerobbery will work for this.

**Comment by MentalIllness** [comment]
The script was tested and the problem was not found. If you still have this issue, feel free to open a new issue also make sure you have the latest version installed.

**Comment by edpimentel** [comment]
We are having the same problem. Every time someone rob a store, a blip spawn on every user with the police job location

**Comment by edpimentel** [comment]
> My server is also having the same issue. I am going to test to see if the same fix from Storerobbery will work for this.

Hi! can you share the link for the storerobbery please
