### ISSUE TITLE
[BUG] Make the hack compatible with AZERTY keyboards

### ISSUE THREAD

**Issue by AntoineKM** [qbcore-framework/qb-bankrobbery#104]
**Describe the bug**
When you start a hack you can be quite surprised by the fact that the hack is made for QWERTY keyboards, so this one is very complicated to realize...

**To Reproduce**
1. Go to the bank
2. Try to open the door to get the door hack
3. Try it with a keyboard in AZERTY

**Expected behavior**
That it is adapted according to the keyboard

**Questions (please complete the following information):**
 - When you last updated: 2 days ago
 - Are you using custom resource? which ones? No
 - Have you renamed `qb-` to something custom? No

**Comment by AntoineKM** [comment]
It seems to be related to `mhacking`

**Comment by xFutte** [comment]
This is an improvement and not a bug.

**Comment by AntoineKM** [comment]
> This is an improvement and not a bug.

To be honest, when I saw that I couldn't solve the hack because I couldn't go left or up I thought that it just didn't work, it's when I looked in the code that I understood that it was related to the fact that my keyboard is in AZERTY, seen like that we can consider it as a bug.
