### ISSUE TITLE
[BUG] - Attempt to index a nil value (Field 'Items')

### ISSUE THREAD

**Issue by ChlxeThomson** [qbcore-framework/qb-bankrobbery#120]
**Describe the bug**
getting the dreaded error as stated in title

**Expected behaviour**
for it to obvs work & no F8 error codes in console

**Screenshots**
<img width="1127" alt="Screenshot 2023-12-29 133447" src="https://github.com/qbcore-framework/qb-bankrobbery/assets/58238399/222b6488-659a-401b-9d90-676d4f984bc0">
<img width="1706" alt="Screenshot 2023-12-29 134715" src="https://github.com/qbcore-framework/qb-bankrobbery/assets/58238399/c26d0be7-7941-48e0-a031-2ce788350c31">
<img width="1171" alt="Screenshot 2023-12-29 135241" src="https://github.com/qbcore-framework/qb-bankrobbery/assets/58238399/5f658a68-c890-420e-a5cd-1d629bfb2bec">

**Questions (please complete the following information):**
 - When you last updated: - Last night
 - Are you using custom resource? - Negative
 - Have you renamed `qb-` to something custom? - Negative

**Additional context**
As you can see i have the item and i have tried all sorts with the code on line 5 in the **Powerstation.Lua** section

**Comment by GhzGarage** [comment]
Come join the discord and we can help you out more, seems like something specific to you happening! discord.gg/qbcore
