### ISSUE TITLE
Vault door Desync

### ISSUE THREAD

**Issue by Rzoned** [qbcore-framework/qb-bankrobbery#14]
when Robbing the banks  the door will open for people in the area but cops who come in who were a couple or more blocks away  will see the vault doors closed 

ive tried with all types of one sync settings

**Comment by vanillla1** [comment]
The problem has been tried
It consists of two types
The first is when the doors are opened, and then the player exits the server and enters again, he will see all the doors closed and the other players see the doors open
Also, sometimes the police and hostages see the doors closed
