### ISSUE TITLE
Bank Says Erro

### ISSUE THREAD

**Issue by cody513** [qbcore-framework/qb-bankrobbery#20]
hello my name is cody and i have been trying to use this every time i try put it in what happens i cart even hack or drill the door open its broken 

[script:qb-bankrobber] Error loading script server/main.lua in resource qb-bankrobbery: @qb-bankrobbery/server/main.lua:190: attempt to index a nil value (global 'QBCore')

i have not touch this file

**Comment by cody513** [comment]
were else can i get this script from

**Comment by JayseeXD** [comment]
Likely caused from not having the framework set up properly... Verify you have followed all the steps... make sure the QBCore script is running on your server... It's a dependency
