### ISSUE TITLE
Pacific Standard Bank Robbery

### ISSUE THREAD

**Issue by SepticLime** [qbcore-framework/qb-bankrobbery#26]
The last 2 gates in the big bank robbery that require thermite do not open upon successful deploying thermite. You receive the notifications the thermite has been planted and the count down but the gate does not unlock. The locks work as PD can lock and unlock these gates the thermite just does not unlock them.

**Comment by SepticLime** [comment]
["thermite"] = {
            [1] = {
                ["coords"] = vector3(252.55, 221.15, 101.68),
                ["isOpened"] = false,
                ["doorId"] = 78
            },
            [2] = {
                ["coords"] = vector3(261.15, 215.21, 101.68),
                ["isOpened"] = false,
                ["doorId"] = 79
            }
        },

These are the 2 gates, I cannot find the ID for these gates anywhere to confirm these are the correct doorID's

**Comment by Synthethics** [comment]
This has already been fixed and a PR for the fix has already been merged with main. The issue was DoorID's being incorrect.
https://github.com/qbcore-framework/qb-bankrobbery/commit/4a6bdc40d9d569b9c30318cea382e35f84a26577
