### ISSUE TITLE
Doors at banks (Paleto and Pac Standard) not opening after Thermite success

### ISSUE THREAD

**Issue by dragon703** [qbcore-framework/qb-bankrobbery#27]
The doors which require thermite to open in banks like Paleto Bay or Pacific Standard, stay locked even after successfully detonating the thermite as shown in required items.

**Comment by GAccountFivem** [comment]
Comparing with the qb-doorlock/config.lua the thermite doorId's are incorrect on the qb-bankrobbery/config.lua

Maybe doorlock could have a method to return the closest door to the player, this way it prevents users from having to do multiple configurations.

**Comment by Synthethics** [comment]
https://github.com/qbcore-framework/qb-bankrobbery/pull/38
Fixed with pull request.

**Comment by akshaynstack** [comment]
I am facing an issue with the same, where can I find qb-doorlock id

**Comment by DopeLovingHippy** [comment]
im having thiss issue now ...did you find a fix ?
