### ISSUE TITLE
current cops

### ISSUE THREAD

**Issue by macxitotruck** [qbcore-framework/qb-bankrobbery#29]
![Screenshot_57](https://user-images.githubusercontent.com/53495532/133717074-1401efef-8ea9-4e32-adfc-1b826a3db2e6.png)

powerstation.lua line 3 . 

local CurrentCops = 0    change to [ CurrentCops = 0 ] then it works again .

**Comment by GhzGarage** [comment]
Was a variable issue. Should be fixed now.
