### ISSUE TITLE
Attempt to Compare number with nil

### ISSUE THREAD

**Issue by rekkaholic** [qbcore-framework/qb-bankrobbery#31]
![image](https://user-images.githubusercontent.com/91042248/133954618-97ddb02d-a328-4ec9-baf4-ca29413662df.png)
 
![image](https://user-images.githubusercontent.com/91042248/133954657-049b0822-8212-459f-bc2d-6b035ceb6dc2.png)

Unable to use Security Card on Paleto door.

**Comment by Synthethics** [comment]
https://github.com/qbcore-framework/qb-bankrobbery/issues/32
Duplicate issue. Runs fine on newest build. Please update or join https://discord.gg/qbcore for more support. Thanks!

**Comment by GhzGarage** [comment]
discord.gg/qbcore
