### ISSUE TITLE
Security card and Eletronic kit

### ISSUE THREAD

**Issue by FlowdGODX** [qbcore-framework/qb-bankrobbery#32]
The first door on pacific bank i can open with the advanced lockpick, but the door that needs security card and the door that needs the eletronic kit, isn't working. it's getting an error on client\pacific.lua:222 attempt to compare number with nil.

**Comment by Synthethics** [comment]
Hey, sorry for the late response. I'm running the latest build and I have no issues with opening the doors with Security Card B or the vault door with Electronic Kit / Trojan USB. They both open normally. What your line is refering to is the Police Required config. Please join discord.gg/qbcore to get more support on this!

**Comment by GhzGarage** [comment]
discord.gg/qbcore

**Comment by Yeti1812** [comment]
Started a new five M server can't seem to find where you actually get the trojan USB or how to obtain it. Can anyone help?
