### ISSUE TITLE
Vault door won't open

### ISSUE THREAD

**Issue by FlowdGODX** [qbcore-framework/qb-bankrobbery#39]
After the minigame, the vault door won't open. and i did a fresh install of qb-doorlock and qb-bankrobber
![unknown](https://user-images.githubusercontent.com/64509394/135701271-9a7bc878-40bf-4d7a-8937-b5f6338e24c7.png)
y

**Comment by Synthethics** [comment]
The vault door opens normally for me, running latest QBCore Build.
