### ISSUE TITLE
Issue with thermite

### ISSUE THREAD

**Issue by tweechimp** [qbcore-framework/qb-bankrobbery#40]
doing the paleto and pacific bank robbery using the thermite when fail the thermite it stun locks the character in animation forcing player to relog

**Comment by Synthethics** [comment]
I've intentionally failed a thermite ignition at Paleto Bay Bank 5 times now and I've not been stun locked in animation. However, I have had issues before that resulted in me dying inbetween the unlockable doors, that's where the glitch stepped in and I had to relog because /revive wouldn't work.

**Comment by tweechimp** [comment]
> I've intentionally failed a thermite ignition at Paleto Bay Bank 5 times now and I've not been stun locked in animation. However, I have had issues before that resulted in me dying inbetween the unlockable doors, that's where the glitch stepped in and I had to relog because /revive wouldn't work.

**Comment by tweechimp** [comment]
im not sure what different about mine then but its not working 

synthethics not sure what you have different but would love to know

**Comment by Synthethics** [comment]
I don't really have anything different, I have the latest build that I pulled a day ago from GitHub via txAdmin as I do every time, it works fine for me. If it doesn't work and you get errors, please join https://discord.gg/qbcore for more help on the matter.
