### ISSUE TITLE
Not starting MHacking for Fleeca Robberies when using electronic kit

### ISSUE THREAD

**Issue by MrMCore** [qbcore-framework/qb-bankrobbery#46]
So I have not had this problem before but now when I got to the Fleeca Banks and try to use the Electronic kit to rob it nothing happens all other robberies work fine. When I use the electronic kit nothing happens no errors in the server or client. It seems to be only Fleeca all others are working and have tested them this was working for me but I was checking it yesterday it did nothing updated the script again to see if same problem which it was. I am using the latest version of QBCore. If you can help me would be deeply appreciated thanks for the amazing work and updates.

**Comment by MrMCore** [comment]
![20211101135232_1](https://user-images.githubusercontent.com/91703151/139682674-50a58bb9-ef7e-4aec-ac8d-5d70b9a58f7b.jpg)
![20211101135235_1](https://user-images.githubusercontent.com/91703151/139682676-82616843-7a0e-40eb-9e0a-86da1ec12254.jpg)

**Comment by MrMCore** [comment]
Also the hacking when doing pacific seems to be same it also runs mhacking if I am correct when I get down to this door I also cant get further
![20211101135502_1](https://user-images.githubusercontent.com/91703151/139682951-990d4270-7e2b-4612-b705-c40c69a1d4e6.jpg)

If you need anything else please let me know thank you

**Comment by Snili866** [comment]
same over here nothing happens when i try too use the electronic kit

**Comment by kassa19951** [comment]
this ti also happen to me

**Comment by Fistsofury** [comment]
@kassa19951 @Snili866 i had this exact same problem and just reinstalled qb-bankrobbery and now works fine.

**Comment by amantu-qbit** [comment]
Same issue. it'll work after ensure qb-bankrobbery. But every time after restart it'll not work. it's not the mhacking.

**Comment by Snili866** [comment]
> @kassa19951 @Snili866 i had this exact same problem and just reinstalled qb-bankrobbery and now works fine.

already tried that but still not working but maybe i did it wrong.
