### ISSUE TITLE
pacific bank thermite door issue

### ISSUE THREAD

**Issue by maminousniper** [qbcore-framework/qb-bankrobbery#52]
![image](https://user-images.githubusercontent.com/34606935/141469768-afa695a1-7b9a-4b57-b1d5-e2d5b6aa2fb2.png)

**Comment by DaShizz** [comment]
^

**Comment by ShaAlexander** [comment]
🆙

**Comment by ShaAlexander** [comment]
QUICK AND DIRTY FIX; Comment the line and the one above it ;-)!

**Comment by DaShizz** [comment]
> QUICK AND DIRTY FIX; Comment the line and the one above it ;-)!

lmao thats exactly what i did yesterday

**Comment by GeekHamza1** [comment]
same issue here

**Comment by jnccloud** [comment]
Latest PR https://github.com/qbcore-framework/qb-bankrobbery/commit/ffbd7eba2cdefb22fbaa58e9dbd35ab5d7f4dca0 should have fixed this issue
