### ISSUE TITLE
Powerstations thermite minigame (openThermite)

### ISSUE THREAD

**Issue by Brusein** [qbcore-framework/qb-bankrobbery#68]
When my server is started with a clear cache the thermite at powerstations just won't work, no error, just won't open mini game. 

If I restart qb-bankrobbery while server is running and try again it works. 

due to my lack of experience I'm not sure what it could be. when looking at the event and the .js

if anyone has fixed this on there server or would like to assist please reach out

**Comment by BerkieBb** [comment]
I'll take a look for you now

**Comment by BerkieBb** [comment]
Did you clear both the server and client cache or only one of the two?

**Comment by BerkieBb** [comment]
I just cleared my servers cache and the thermite works just as normal

**Comment by Brusein** [comment]
It's so strange, server and client clean startup and it doesn't work, restart resource on the fly and it works, the mini game will open.

I'll do some more testing, I just don't know what would cause it. No error message of course. 

Thank you for looking B

**Comment by Brusein** [comment]
@BerkieBb I tried it again in 1080, 1440, and other resolutions to verify it wasn't a weird thing with that and still have the issue, 

It's so weird, I can /restart the resource and it starts working. The mini game is just managed in the .js with no dependency from what I can tell, I searched my files for some conflict with the function and can't find it. Not sure what to do now.

Any ideas of things I could try?

**Comment by Brusein** [comment]
So now with the recent update I retested and on a fresh server start up there thermite game doesn't open at all. 

I have no idea why this happens on my server it's like it doesn't do the click and therefore open the thermite mini game. 

If I restart the script once server loaded works perfectly fine. 

Let me know if you have any clue what would cause this

**Comment by GhzGarage** [comment]
@BerkieBb
