### ISSUE TITLE
Hacky no Worky

### ISSUE THREAD

**Issue by clmillzz** [qbcore-framework/qb-bankrobbery#71]
**Describe the bug**
Using the Electronic Kit on the bank doors doesn't prompt the minigame to open it. Server restart, no errors, police needed set to 0, on duty officer just in case.

**To Reproduce**
1. Go to Bank
2. Use Electronic Kit
3. That's it

**Expected behavior**
Minigame to hack into door 

**Screenshots**
Not Applicable

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] - A week ago, this script today
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] - both listed and many more, nothing that interferes with this one
 - Have you renamed `qb-` to something custom? [e.g. yes/no] - no

**Comment by vBooya** [comment]
Also, no notification with police set to 0 or 3 saying police needed

**Comment by BerkieBb** [comment]
> Also, no notification with police set to 0 or 3 saying police needed

I tested it and it was working, you need mhacking for it to work which comes with the recipe, https://github.com/qbcore-framework/mhacking

**Comment by Hobby-Less** [comment]
I am also having this issue even with the mhacking script

**Comment by Hobby-Less** [comment]
I only tried the fleeca and pacific and both of them do not work. I have reinstalled both qb-bankrobbery and mhacking to see if that would fix my problem. But that does not help either.

**Comment by BerkieBb** [comment]
I'll test it later to see if I can reproduce this isuse

**Comment by aklu0830** [comment]
Did someone fix this

**Comment by BerkieBb** [comment]
I forgot to test it, tomorrow I do have time to test it and fix it

**Comment by gypsychicken** [comment]
same issue, please let us know when a fix is available.

**Comment by TheOldHook** [comment]
Same issue, fix coming?

**Comment by BerkieBb** [comment]
Fix is coming in a few hours

**Comment by BerkieBb** [comment]
Fixed ^^

**Comment by TheOldHook** [comment]
BerkieBb got this fixed, but now i have another problem and that is the first door (now tested Pacific) don't get option to use thermite. Second door with security card and next with electronic kit and USB works fine.
