### ISSUE TITLE
[BUG] You can drill 6-8 times again and again on same Locker At Paleto + Fleeca

### ISSUE THREAD

**Issue by subhampro** [qbcore-framework/qb-bankrobbery#79]
*[BUG] You can drill 6-8 times again and again on same Locker At Paleto + Fleeca

Please Fix It .Its Multiply Bank robbery rewards

**Comment by BerkieBb** [comment]
I can't seem to reproduce this, I can only rob any locker one time, with the target option and without it, both work as expected

**Comment by BerkieBb** [comment]
I was able to reproduce it at fleeca

**Comment by subhampro** [comment]
> I can't seem to reproduce this, I can only rob any locker one time, with the target option and without it, both work as expected

In the script There is "PRESS E to SEARCH" option !! there is no target option in the leatest Script !!!


> I was able to reproduce it at fleeca



I will upload a Video ASAP !!

**Comment by BerkieBb** [comment]
No need, I fixed it already

**Comment by BerkieBb** [comment]
> In the script There is "PRESS E to SEARCH" option !! there is no target option in the leatest Script !!!

There is but you need to make sure `setr UseTarget true` is in your server.cfg to enable the option

**Comment by subhampro** [comment]
> > In the script There is "PRESS E to SEARCH" option !! there is no target option in the leatest Script !!!
> 
> There is but you need to make sure `setr UseTarget true` is in your server.cfg to enable the option

Got It  let me try and then I will close the issue

**Comment by subhampro** [comment]
Fixed Thanks
