### ISSUE TITLE
[BUG] Possible problem witth thermite door on Pacific Bank and lockpick.

### ISSUE THREAD

**Issue by H1deMyFace** [qbcore-framework/qb-bankrobbery#83]
**Describe the bug 1**
When you use the thermite on the power station the door inside Pacific Bank bug thinking I'm using the power station.

**Describe the bug 2**
When you use the lockpick in Pacific Bank it is sometimes not removed from the inventory and the player uses as many times he wants.

**To Reproduce**
1. Go to power station then use the thermite.
2. Indifferent if the power are off or on, go to Pacific Bank and make the puzzles.
3. When you reach the thermite door the script send the notify: "The fuses are broken" and not open the door.

**To Reproduce 2**
1. Try to use the lockpick and fail on the door.
2. The lockpick sometimes got not removed from inventory and the player uses as many times he want.

**Expected behavior**
Problem 1: Open the thermite door.
Problem 2: Remove one lockpick everytime the player fail or win the puzzle.

**Screenshots**
https://imgur.com/a/BHZa0kp

**Questions (please complete the following information):**
 - When you last updated: Today I have downloaded again the bank robbery and all qbcore script I use is from the last recommended build 5562.
 - Are you using custom resource? which ones? Only one script to change the density of Npcs, discordlogs and the rest is fully qbcore with txAdmin.
 - Have you renamed `qb-` to something custom? No.

**Additional context**
The only error is of the inventory but if I remember it's not related with the bank robbery. This problems happens so much times.
The lockpick problem I don't know if it was really supposed to be like this or should always consume one.
I don't have much time to look at the code and confirm this but I will help with whatever is needed and if it's not a bug I'm sorry for asking for help.
For now, thanks.

**Comment by xtxvxtx** [comment]
Having an Issue with the first thermite door in Pacific Bank.
![image](https://user-images.githubusercontent.com/105738467/169931095-a92cc337-a444-4fb5-abb5-1fbf8da5313d.png)

**Comment by BerkieBb** [comment]
> When you use the lockpick in Pacific Bank it is sometimes not removed from the inventory and the player uses as many times he wants.

This is not a bug, this is a feature of qb-doorlock, it only removes the lockpick by chance

**Comment by BerkieBb** [comment]
> Having an Issue with the first thermite door in Pacific Bank. ![image](https://user-images.githubusercontent.com/105738467/169931095-a92cc337-a444-4fb5-abb5-1fbf8da5313d.png)

Update your qb-core

**Comment by BerkieBb** [comment]
> When you reach the thermite door the script send the notify: "The fuses are broken" and not open the door.

Have you been to any of the power stations before doing this?

**Comment by H1deMyFace** [comment]
> > When you reach the thermite door the script send the notify: "The fuses are broken" and not open the door.
> 
> Have you been to any of the power stations before doing this?

Yes, I go to the ps and try a little. Afer I go to bank and try all the puzzles but when I reach the thermite the script get lost and believe I am in the ps.

**Comment by BerkieBb** [comment]
> > > When you reach the thermite door the script send the notify: "The fuses are broken" and not open the door.
> > 
> > 
> > Have you been to any of the power stations before doing this?
> 
> Yes, I go to the ps and try a little. Afer I go to bank and try all the puzzles but when I reach the thermite the script get lost and believe I am in the ps.

I tried to reproduce it by going to a powerstation and teleporting to the pacific bank but this didn't seem to bug, it opened the door fine and gave me the right notification

**Comment by H1deMyFace** [comment]
> 

I wanna send a vid for u later. I didn't changed nothing on the lines of code. I have downloaded again the entire script but the same problem. Let me record the video.

**Comment by H1deMyFace** [comment]
Here:

https://streamable.com/563kmw

**Comment by H1deMyFace** [comment]
Thank you
