### ISSUE TITLE
The Required items are getting deleted irrespective of their count

### ISSUE THREAD

**Issue by krizmatic** [qbcore-framework/qb-bankrobbery#9]
When we initiate a robbery, the whole amount of the required items (like electronic kit , trojan usb,etc) will get deleted irrespective of their amount. For example , If you have 10 electronic kit and after initiating the robbery,the whole 10 electronic kit will get deleted.

**Comment by BerkieBb** [comment]
That is pretty weird as it's written in qb-bankrobbery/client/fleeca.lua under the useElectronickit event that it will only delete one

**Comment by BerkieBb** [comment]
It might be that you spammed it and it removed it so much times that it deleted it all times because it also doesn't run in a loop so it only gets triggered once

**Comment by krizmatic** [comment]
We can't spam it brother. The items are used using inventory right.

**Comment by BerkieBb** [comment]
You can spam the keybind when it's in the hotbar but try to re-download it and check if it still does that

**Comment by Yeti1812** [comment]
Started a new five M server can't seem to find where you actually get the trojan USB or how to obtain it. Can anyone help?
